require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BreezeCategoriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # BreezeCategory. As you add validations to BreezeCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {:name => 'Some Category', :description => 'A lot of text',
     :image => File.open(Rails.root.join('spec/fixtures/files/upload.jpg')),
     }
  }

  let(:invalid_attributes) {
    {:name => '', :description => 'A lot of text'}
  }


  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BreezeCategoriesController. Be sure to keep this updated too.
  describe 'Admin' do

    login_admin


    describe "GET index" do
      it "assigns breeze_categoires as @breeze_categoires with pagination" do
        BreezeCategory.create! valid_attributes
        breeze_categories = BreezeCategory.all
        get :index, {}
        expect(assigns(:breeze_categories)).to eq(breeze_categories)
      end
    end

    describe "GET show" do
      it "assigns the requested breeze_category as @breeze_category" do
        breeze_category = BreezeCategory.create! valid_attributes
        get :show, {:id => breeze_category.to_param}
        expect(assigns(:breeze_category)).to eq(breeze_category)
      end
    end

    describe "GET new" do
      it "assigns a new breeze_category as @breeze_category" do
        get :new, {}
        expect(assigns(:breeze_category)).to be_a_new(BreezeCategory)
      end
    end

    describe "GET edit" do
      it "assigns the requested breeze_category as @breeze_category" do
        breeze_category = BreezeCategory.create! valid_attributes
        get :edit, {:id => breeze_category.to_param}
        expect(assigns(:breeze_category)).to eq(breeze_category)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new BreezeCategory" do
          expect {
            post :create, {:breeze_category => valid_attributes}
          }.to change(BreezeCategory, :count).by(1)
        end

        it "assigns a newly created breeze_category as @breeze_category" do
          post :create, {:breeze_category => valid_attributes}
          expect(assigns(:breeze_category)).to be_a(BreezeCategory)
          expect(assigns(:breeze_category)).to be_persisted
        end

        it "redirects to the created breeze_category" do
          post :create, {:breeze_category => valid_attributes}
          expect(response).to redirect_to(BreezeCategory.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved breeze_category as @breeze_category" do
          post :create, {:breeze_category => invalid_attributes}
          expect(assigns(:breeze_category)).to be_a_new(BreezeCategory)
        end

        it "re-renders the 'new' template" do
          post :create, {:breeze_category => invalid_attributes}
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          { :name => 'Changed Category II', :description => 'Changed description' }
        }

        it "updates the requested breeze_category" do
          breeze_category = BreezeCategory.create! valid_attributes
          put :update, {:id => breeze_category.id, :breeze_category => new_attributes}
          breeze_category.reload
          expect(response).to redirect_to(BreezeCategory.last)
        end

        it "assigns the requested breeze_category as @breeze_category" do
          breeze_category = BreezeCategory.create! valid_attributes
          put :update, {:id => breeze_category.to_param, :breeze_category => new_attributes}
          expect(assigns(:breeze_category)).to eq(breeze_category)
        end

        it "redirects to the breeze_category" do
          breeze_category = BreezeCategory.create! valid_attributes
          put :update, {:id => breeze_category.to_param, :breeze_category => new_attributes}
          expect(response).to redirect_to(breeze_category)
        end
      end

      describe "with invalid params" do
        it "assigns the breeze_category as @breeze_category" do
          breeze_category = BreezeCategory.create! valid_attributes
          put :update, {:id => breeze_category.to_param, :breeze_category => invalid_attributes}
          expect(assigns(:breeze_category)).to eq(breeze_category)
        end

        it "re-renders the 'edit' template" do
          breeze_category = BreezeCategory.create! valid_attributes
          put :update, {:id => breeze_category.to_param, :breeze_category => invalid_attributes}
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested breeze_category" do
        breeze_category = BreezeCategory.create! valid_attributes
        expect {
          delete :destroy, {:id => breeze_category.to_param}
        }.to change(BreezeCategory, :count).by(-1)
      end

      it "redirects to the breeze_categoires list" do
        breeze_category = BreezeCategory.create! valid_attributes
        delete :destroy, {:id => breeze_category.to_param}
        expect(response).to redirect_to(breeze_categories_url)
      end
    end
  end




  describe 'User' do

    login_user


    describe "GET index" do
      it "assigns all breeze_categoires as @breeze_categoires" do
        breeze_categories = BreezeCategory.all
        get :index, {}
        expect(assigns(:breeze_categories)).to eq( breeze_categories)
      end
    end

    describe "GET show" do
      it "assigns the requested breeze_category as @breeze_category" do
        breeze_category = BreezeCategory.create! valid_attributes
        get :show, {:id => breeze_category.to_param}
        expect(assigns(:breeze_category)).to eq(breeze_category)
      end
    end

    describe "GET new" do
      it "assigns a new breeze_category as @breeze_category" do
        get :new, {}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end

    describe "GET edit" do
      it "assigns the requested breeze_category as @breeze_category" do
        breeze_category = BreezeCategory.create! valid_attributes
        get :edit, {:id => breeze_category.to_param}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "doesn't create a new BreezeCategory" do
          expect {
            post :create, {:breeze_category => valid_attributes}
          }.to change(BreezeCategory, :count).by(0)
        end

        it "redirects to the site root with flash-alert" do
          post :create, {:breeze_category => valid_attributes}
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          {:name => 'Changed Category II', :description => 'Changed description', :parent_id => 2}
        }

        it "does not update the requested breeze_category" do
          breeze_category = BreezeCategory.create! valid_attributes
          put :update, {:id => breeze_category.id, :breeze_category => new_attributes}
          breeze_category.reload
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end

        it "redirects to the site_root with flash-alert" do
          breeze_category = BreezeCategory.create! valid_attributes
          put :update, {:id => breeze_category.to_param, :breeze_category => new_attributes}
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested breeze_category" do
        breeze_category = BreezeCategory.create! valid_attributes
        expect {
          delete :destroy, {:id => breeze_category.to_param}
        }.to change(BreezeCategory, :count).by(0)
      end

      it "redirects to the site root with flash-alert" do
        breeze_category = BreezeCategory.create! valid_attributes
        delete :destroy, {:id => breeze_category.to_param}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end
  end

end
