require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ImageGalleriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ImageGalleryCategory. As you add validations to ImageGalleryCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes){
    {
        :title => 'Title',
        :description => 'Some description',
        :media_image_category_id => 1
    }
  }

  let(:gallery_images){
    {
        :images => [
            File.open(Rails.root.join('spec/fixtures/files/upload.jpg')),
            File.open(Rails.root.join('spec/fixtures/files/upload.jpg')),
        ]
    }
  }

  let(:invalid_attributes) {
    {:title => '' }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ImageGalleryCategoriesController. Be sure to keep this updated too.
  describe 'Admin' do

  login_admin

    describe "GET show" do
      it "assigns the requested image_gallery as @image_gallery" do
        image_gallery = ImageGallery.create! valid_attributes
        get :show, {:id => image_gallery.to_param}
        expect(assigns(:image_gallery)).to eq(image_gallery)
      end
    end

    describe "GET edit" do
      it "assigns the requested image_gallery as @image_gallery" do
        image_gallery = ImageGallery.create! valid_attributes
        get :edit, {:id => image_gallery.to_param}
        expect(assigns(:image_gallery)).to eq(image_gallery)
      end
    end

    describe "GET #new" do
      it "assigns a new ImageGallery as @image_gallery" do
        get :new, {}
        expect(assigns(:image_gallery)).to be_a_new(ImageGallery)
      end
    end

  describe "POST #create" do
    context "with valid params" do
      describe "creates a new ImageGallery" do
        it "with image gallery" do
          expect {
            post :create, {:image_gallery => valid_attributes, :gallery_images => gallery_images}
          }.to change(ImageGallery, :count).by(1)
        end
      end

      it "assigns a newly created image_gallery as @image_gallery" do
        post :create, {:image_gallery => valid_attributes}
        expect(assigns(:image_gallery)).to be_a(ImageGallery)
        expect(assigns(:image_gallery)).to be_persisted
      end
      it "redirects to the created image_gallery" do
        post :create, {:image_gallery => valid_attributes}
        expect(response).to redirect_to(ImageGallery.last)
      end
    end
    context "with invalid params" do
      it "assigns a newly created but unsaved image_gallery as @image_gallery" do
        post :create, {:image_gallery => invalid_attributes}
        expect(assigns(:image_gallery)).to be_a_new(ImageGallery)
      end

      it "re-renders the 'new' template" do
        post :create, {:image_gallery => invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          { :name => 'New Name',
            :email => 'new_email@mail.ru',
            :web => 'http://new-webaddress.ru',
            :fb => 'http://new-fb.com/image_gallery',
            :image_gallery_category_id => 1,
            :level1_description => 'Description level 01',
            :level2_description => 'Description level 02',
            :level3_description => 'Description level 03',
            :airport  => 'Milan Airport',
            :altitude_top => 4000,
            :altitude_bottom => 2000,
            :drop => 250,
            :terrain  => 200,
            :lifts  => 5,
            :slopes => '11/31/61',
            :map_url => 'http://new-image_gallerymap.url'
          }
        }

        it "updates the requested image_gallery" do
          image_gallery = ImageGallery.create! valid_attributes
          put :update, {:id => image_gallery.id, :image_gallery => new_attributes}
          image_gallery.reload
          expect(response).to redirect_to(ImageGallery.last)
        end

        it "assigns the requested image_gallery as @image_gallery" do
          image_gallery = ImageGallery.create! valid_attributes
          put :update, {:id => image_gallery.to_param, :image_gallery => new_attributes}
          expect(assigns(:image_gallery)).to eq(image_gallery)
        end

        it "redirects to the image_gallery" do
          image_gallery = ImageGallery.create! valid_attributes
          put :update, {:id => image_gallery.to_param, :image_gallery => new_attributes}
          expect(response).to redirect_to(image_gallery)
        end
      end
    end

  describe "DELETE destroy" do
    it "destroys the requested image_gallery" do
      image_gallery = ImageGallery.create! valid_attributes
      expect {
        delete :destroy, {:id => image_gallery.to_param}
      }.to change(ImageGallery, :count).by(-1)
    end

    it "redirects to the image_galleries list" do
      image_gallery = ImageGallery.create! valid_attributes
      delete :destroy, {:id => image_gallery.to_param}
      expect(response).to redirect_to(image_galleries_url)
    end
  end
    
  end

  describe 'Not Admin' do

    login_user

    describe "GET show" do
      it "assigns the requested image_gallery as @image_gallery" do
        image_gallery = ImageGallery.create! valid_attributes
        get :show, {:id => image_gallery.to_param}
        expect(assigns(:image_gallery)).to eq(image_gallery)
      end
    end

    describe "GET edit" do
      it "assigns the requested image_gallery as @image_gallery" do
        image_gallery = ImageGallery.create! valid_attributes
        get :edit, {:id => image_gallery.to_param}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          { :name => 'New Name',
            :email => 'new_email@mail.ru',
          }
        }

        it "redirect with no access" do
          image_gallery = ImageGallery.create! valid_attributes
          put :update, {:id => image_gallery.id, :image_gallery => new_attributes}
          image_gallery.reload
          expect(assigns(:image_gallery)).to eq(image_gallery)
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end
      end
    end

    describe "DELETE destroy" do
      it "NO destroys the requested image_gallery" do
        image_gallery = ImageGallery.create! valid_attributes
        expect {
          delete :destroy, {:id => image_gallery.to_param}
        }.to change(ImageGallery, :count).by(0)
      end

      it "NO redirects to the image_galleries list" do
        image_gallery = ImageGallery.create! valid_attributes
        delete :destroy, {:id => image_gallery.to_param}
        expect(assigns(:image_gallery)).to eq(image_gallery)
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end

  end
  
  

end