require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TipCategoriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TipCategory. As you add validations to TipCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {:name => 'Some Category', :description => 'A lot of text',
     :image => File.open(Rails.root.join('spec/fixtures/files/upload.jpg')),
     :slug => 'a-lot-of-text'
     }
  }

  let(:invalid_attributes) {
    {:name => '', :description => 'A lot of text'}
  }


  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipCategoriesController. Be sure to keep this updated too.
  describe 'Admin' do

    login_admin


    describe "GET index" do
      it "assigns tip_categories as @tip_categories with pagination" do

        tip_categories = TipCategory.all
        get :index, {}
        expect(assigns(:tip_categories)).to eq(tip_categories)
      end
    end

    describe "GET show" do
      it "assigns the requested tip_category as @tip_category" do
        tip_category = TipCategory.create! valid_attributes
        get :show, {:id => tip_category.to_param}
        expect(assigns(:tip_category)).to eq(tip_category)
      end
    end

    describe "GET new" do
      it "assigns a new tip_category as @tip_category" do
        get :new, {}
        expect(assigns(:tip_category)).to be_a_new(TipCategory)
      end
    end

    describe "GET edit" do
      it "assigns the requested tip_category as @tip_category" do
        tip_category = TipCategory.create! valid_attributes
        get :edit, {:id => tip_category.to_param}
        expect(assigns(:tip_category)).to eq(tip_category)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new TipCategory" do
          expect {
            post :create, {:tip_category => valid_attributes}
          }.to change(TipCategory, :count).by(1)
        end

        it "assigns a newly created tip_category as @tip_category" do
          post :create, {:tip_category => valid_attributes}
          expect(assigns(:tip_category)).to be_a(TipCategory)
          expect(assigns(:tip_category)).to be_persisted
        end

        it "redirects to the created tip_category" do
          post :create, {:tip_category => valid_attributes}
          expect(response).to redirect_to(TipCategory.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved tip_category as @tip_category" do
          post :create, {:tip_category => invalid_attributes}
          expect(assigns(:tip_category)).to be_a_new(TipCategory)
        end

        it "re-renders the 'new' template" do
          post :create, {:tip_category => invalid_attributes}
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          { :name => 'Changed Category II', :description => 'Changed description' }
        }

        it "updates the requested tip_category" do
          tip_category = TipCategory.create! valid_attributes
          put :update, {:id => tip_category.id, :tip_category => new_attributes}
          tip_category.reload
          expect(response).to redirect_to(TipCategory.last)
        end

        it "assigns the requested tip_category as @tip_category" do
          tip_category = TipCategory.create! valid_attributes
          put :update, {:id => tip_category.to_param, :tip_category => new_attributes}
          expect(assigns(:tip_category)).to eq(tip_category)
        end

        it "redirects to the tip_category" do
          tip_category = TipCategory.create! valid_attributes
          put :update, {:id => tip_category.to_param, :tip_category => new_attributes}
          expect(response).to redirect_to(tip_category)
        end
      end

      describe "with invalid params" do
        it "assigns the tip_category as @tip_category" do
          tip_category = TipCategory.create! valid_attributes
          put :update, {:id => tip_category.to_param, :tip_category => invalid_attributes}
          expect(assigns(:tip_category)).to eq(tip_category)
        end

        it "re-renders the 'edit' template" do
          tip_category = TipCategory.create! valid_attributes
          put :update, {:id => tip_category.to_param, :tip_category => invalid_attributes}
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested tip_category" do
        tip_category = TipCategory.create! valid_attributes
        expect {
          delete :destroy, {:id => tip_category.to_param}
        }.to change(TipCategory, :count).by(-1)
      end

      it "redirects to the tip_categories list" do
        tip_category = TipCategory.create! valid_attributes
        delete :destroy, {:id => tip_category.to_param}
        expect(response).to redirect_to(tip_categories_url)
      end
    end

    it_behaves_like 'slugs_preview'
  end

  describe 'User' do

    login_user

    describe "GET index" do
      it "assigns all tip_categories as @tip_categories" do
        tip_categories = TipCategory.all
        get :index, {}
        expect(assigns(:tip_categories)).to eq( tip_categories)
      end
    end

    describe "GET show" do
      it "assigns the requested tip_category as @tip_category" do
        tip_category = TipCategory.create! valid_attributes
        get :show, {:id => tip_category.to_param}
        expect(assigns(:tip_category)).to eq(tip_category)
      end
    end

    describe "GET new" do
      it "assigns a new tip_category as @tip_category" do
        get :new, {}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end

    describe "GET edit" do
      it "assigns the requested tip_category as @tip_category" do
        tip_category = TipCategory.create! valid_attributes
        get :edit, {:id => tip_category.to_param}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "doesn't create a new TipCategory" do
          expect {
            post :create, {:tip_category => valid_attributes}
          }.to change(TipCategory, :count).by(0)
        end

        it "redirects to the site root with flash-alert" do
          post :create, {:tip_category => valid_attributes}
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          {:name => 'Changed Category II', :description => 'Changed description', :parent_id => 2}
        }

        it "does not update the requested tip_category" do
          tip_category = TipCategory.create! valid_attributes
          put :update, {:id => tip_category.id, :tip_category => new_attributes}
          tip_category.reload
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end

        it "redirects to the site_root with flash-alert" do
          tip_category = TipCategory.create! valid_attributes
          put :update, {:id => tip_category.to_param, :tip_category => new_attributes}
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested tip_category" do
        tip_category = TipCategory.create! valid_attributes
        expect {
          delete :destroy, {:id => tip_category.to_param}
        }.to change(TipCategory, :count).by(0)
      end

      it "redirects to the site root with flash-alert" do
        tip_category = TipCategory.create! valid_attributes
        delete :destroy, {:id => tip_category.to_param}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end
  end

end
