require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe VideoCategoriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # VideoCategory. As you add validations to VideoCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {:name => 'Some Category', :description => 'A lot of text',
     :image => File.open(Rails.root.join('spec/fixtures/files/upload.jpg')),
     }
  }

  let(:invalid_attributes) {
    {:name => '', :description => 'A lot of text'}
  }


  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VideoCategoriesController. Be sure to keep this updated too.
  describe 'Admin' do

    login_admin


    describe "GET index" do
      it "assigns video_categories as @video_categories with pagination" do

        video_categories = VideoCategory.all
        get :index, {}
        expect(assigns(:video_categories)).to eq(video_categories)
      end
    end

    describe "GET show" do
      it "assigns the requested video_category as @video_category" do
        video_category = VideoCategory.create! valid_attributes
        get :show, {:id => video_category.to_param}
        expect(assigns(:video_category)).to eq(video_category)
      end
    end

    describe "GET new" do
      it "assigns a new video_category as @video_category" do
        get :new, {}
        expect(assigns(:video_category)).to be_a_new(VideoCategory)
      end
    end

    describe "GET edit" do
      it "assigns the requested video_category as @video_category" do
        video_category = VideoCategory.create! valid_attributes
        get :edit, {:id => video_category.to_param}
        expect(assigns(:video_category)).to eq(video_category)
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "creates a new VideoCategory" do
          expect {
            post :create, {:video_category => valid_attributes}
          }.to change(VideoCategory, :count).by(1)
        end

        it "assigns a newly created video_category as @video_category" do
          post :create, {:video_category => valid_attributes}
          expect(assigns(:video_category)).to be_a(VideoCategory)
          expect(assigns(:video_category)).to be_persisted
        end

        it "redirects to the created video_category" do
          post :create, {:video_category => valid_attributes}
          expect(response).to redirect_to(VideoCategory.last)
        end
      end

      describe "with invalid params" do
        it "assigns a newly created but unsaved video_category as @video_category" do
          post :create, {:video_category => invalid_attributes}
          expect(assigns(:video_category)).to be_a_new(VideoCategory)
        end

        it "re-renders the 'new' template" do
          post :create, {:video_category => invalid_attributes}
          expect(response).to render_template("new")
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          { :name => 'Changed Category II', :description => 'Changed description' }
        }

        it "updates the requested video_category" do
          video_category = VideoCategory.create! valid_attributes
          put :update, {:id => video_category.id, :video_category => new_attributes}
          video_category.reload
          expect(response).to redirect_to(VideoCategory.last)
        end

        it "assigns the requested video_category as @video_category" do
          video_category = VideoCategory.create! valid_attributes
          put :update, {:id => video_category.to_param, :video_category => new_attributes}
          expect(assigns(:video_category)).to eq(video_category)
        end

        it "redirects to the video_category" do
          video_category = VideoCategory.create! valid_attributes
          put :update, {:id => video_category.to_param, :video_category => new_attributes}
          expect(response).to redirect_to(video_category)
        end
      end

      describe "with invalid params" do
        it "assigns the video_category as @video_category" do
          video_category = VideoCategory.create! valid_attributes
          put :update, {:id => video_category.to_param, :video_category => invalid_attributes}
          expect(assigns(:video_category)).to eq(video_category)
        end

        it "re-renders the 'edit' template" do
          video_category = VideoCategory.create! valid_attributes
          put :update, {:id => video_category.to_param, :video_category => invalid_attributes}
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested video_category" do
        video_category = VideoCategory.create! valid_attributes
        expect {
          delete :destroy, {:id => video_category.to_param}
        }.to change(VideoCategory, :count).by(-1)
      end

      it "redirects to the video_categories list" do
        video_category = VideoCategory.create! valid_attributes
        delete :destroy, {:id => video_category.to_param}
        expect(response).to redirect_to(video_categories_url)
      end
    end
  end




  describe 'User' do

    login_user


    describe "GET index" do
      it "assigns all video_categories as @video_categories" do
        video_categories = VideoCategory.all
        get :index, {}
        expect(assigns(:video_categories)).to eq( video_categories)
      end
    end

    describe "GET show" do
      it "assigns the requested video_category as @video_category" do
        video_category = VideoCategory.create! valid_attributes
        get :show, {:id => video_category.to_param}
        expect(assigns(:video_category)).to eq(video_category)
      end
    end

    describe "GET new" do
      it "assigns a new video_category as @video_category" do
        get :new, {}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end

    describe "GET edit" do
      it "assigns the requested video_category as @video_category" do
        video_category = VideoCategory.create! valid_attributes
        get :edit, {:id => video_category.to_param}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end

    describe "POST create" do
      describe "with valid params" do
        it "doesn't create a new VideoCategory" do
          expect {
            post :create, {:video_category => valid_attributes}
          }.to change(VideoCategory, :count).by(0)
        end

        it "redirects to the site root with flash-alert" do
          post :create, {:video_category => valid_attributes}
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end
      end
    end

    describe "PUT update" do
      describe "with valid params" do
        let(:new_attributes) {
          {:name => 'Changed Category II', :description => 'Changed description', :parent_id => 2}
        }

        it "does not update the requested video_category" do
          video_category = VideoCategory.create! valid_attributes
          put :update, {:id => video_category.id, :video_category => new_attributes}
          video_category.reload
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end

        it "redirects to the site_root with flash-alert" do
          video_category = VideoCategory.create! valid_attributes
          put :update, {:id => video_category.to_param, :video_category => new_attributes}
          expect(response).to redirect_to( root_path )
          expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
        end
      end
    end

    describe "DELETE destroy" do
      it "destroys the requested video_category" do
        video_category = VideoCategory.create! valid_attributes
        expect {
          delete :destroy, {:id => video_category.to_param}
        }.to change(VideoCategory, :count).by(0)
      end

      it "redirects to the site root with flash-alert" do
        video_category = VideoCategory.create! valid_attributes
        delete :destroy, {:id => video_category.to_param}
        expect(response).to redirect_to( root_path )
        expect( response.request.flash[:alert] ).to eq('You are not authorized to access this page.')
      end
    end
  end

end
